[package]
name = "adventofcode-2022"
description = """
    Solutions to Advent of Code 2022 puzzles
"""
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
