[tools]
java = "24"

[tasks.day01]
run = "java --source 24 --enable-preview --class-path 'src/*' src/Day01.java"

[tasks.day02]
run = "java --source 24 --enable-preview --class-path 'src/*' src/Day02.java"

[tasks.day03]
run = "java --source 24 --enable-preview --class-path 'src/*' src/Day03.java"

[tasks.day04]
run = "java --source 24 --enable-preview --class-path 'src/*' src/Day04.java"
